server:
  port: 8081
spring:
  application:
    name: main-part
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kingofschlor?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: jianghao5719
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

