server:
  port: 7001
spring:
  application:
    name: gate-way
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true